Update create

diff --git a/modules/create b/modules/create
--- a/modules/create
+++ b/modules/create
@@ -78,6 +78,12 @@ if ! lxc image list | grep -oq $alias; then
         echo "Error: Invalid image selection"
         exit
     fi
+    # Verify connectivity before proceeding
+    while ! ping -c 1 -W 1 cloud-images.ubuntu.com > /dev/null 2>&1; do
+        echo "Network: Unable to reach cloud-images.ubuntu.com"
+        sleep 3
+    done
+    # Copy remote image to the local image store
     echo "Downloading image"
     lxc image copy $image local: --alias $alias --auto-update
 fi
