Update archive-connect

diff --git a/lib/archive-connect b/lib/archive-connect
--- a/lib/archive-connect
+++ b/lib/archive-connect
@@ -1,8 +1,18 @@
 #!/bin/bash
 
 archive-connect () {
-  while ! ping -c 3 -W 1 archive.ubuntu.com > /dev/null 2>&1; do
-    echo "Network: Unable to reach archive.ubuntu.com"
-    sleep 3
-  done
+  if dpkg-query -l | grep -oq iputils-ping; then
+    while ! ping -c 3 -W 1 archive.ubuntu.com > /dev/null 2>&1; do
+      echo "Network: Unable to reach archive.ubuntu.com"
+      sleep 3
+    done
+  else
+    echo "Installing iputils-ping"
+    apt-get -y update &> /dev/null
+    apt-get -y install iputils-ping &> /dev/null || echo "Error: Failed to install iputils-ping" && exit
+    while ! ping -c 3 -W 1 archive.ubuntu.com > /dev/null 2>&1; do
+      echo "Network: Unable to reach archive.ubuntu.com"
+      sleep 3
+    done
+  fi
 }
