Update config

diff --git a/scripts/config b/scripts/config
--- a/scripts/config
+++ b/scripts/config
@@ -11,10 +11,10 @@ if [ -d /snap/lxd ]; then
 fi
 
 # Verify connectivity before proceeding
-while ! ping -c 1 -W 1 archive.ubuntu.com > /dev/null 2>&1; do
-    echo "Network: Unable to reach archive.ubuntu.com"
-    sleep 3
-done
+#while ! ping -c 1 -W 1 archive.ubuntu.com > /dev/null 2>&1; do
+#    echo "Network: Unable to reach archive.ubuntu.com"
+#    sleep 3
+#done
 
 # Get the current hostname
 alias="$(cat /etc/hostname)"
