Update dhcpd

diff --git a/scripts/dhcpd b/scripts/dhcpd
--- a/scripts/dhcpd
+++ b/scripts/dhcpd
@@ -4,7 +4,20 @@
 ##### Install dhcpd (Ubuntu 18.04) #####
 ########################################
 
+# Perform a crude check to make sure the script is not running on a host system
+if [ -d /snap/lxd ]; then
+    echo "Error: Do not run on a host system"
+    exit
+fi
+
+# Verify connectivity before proceeding
+while ! ping -c 1 -W 1 archive.ubuntu.com > /dev/null 2>&1; do
+    echo "Network: Unable to reach archive.ubuntu.com"
+    sleep 3
+done
+
 # Install the dhcpd package
+apt update -y
 apt install -y isc-dhcp-server
 
 # Add the interface to the defaults file
